### ISSUE TITLE
Bower registry points to outdated fork

### ISSUE THREAD

**Issue by binoculars** [Polymer/hydrolysis#232]
@danielbaak can you please unregister `hydrolysis` with bower so that it can registered to Polymer/hydrolysis? I'm asking because it makes replicating the registry to an offline network difficult.

**Comment by danielbaak** [comment]
@binoculars your wish is my command.  

I had only registered my fork because I didn't know how to register the official package. Not quite sure if it's correct now ...

     -> bower search hydrolysis
     Search results:

     hydrolysis git://github.com/Polymer/hydrolysis.git

for some reason doing `bower info hydrolysis` still seems to find information on my fork, and also `bower info Polymer/hydrolysis` returns information on the official repo. 

Does this work for you?

**Comment by binoculars** [comment]
@danielbaak Yes, it resolves to the main Polymer repo now. Thanks so much. :smile:  Btw if you run `bower clean cache && bower lookup hydrolysis`, you should see it pointing to the correct repo. :trophy:
